---
    
- name: 'Replace config'
  template:
    src: 'application.yml.j2'
    dest: '/opt/service-two-epam/src/main/resources/application.yml'

- name: 'Maven clean package'
  command: 'sudo mvn -f /opt/service-two-epam/pom.xml clean package'

- name: 'Create service'
  template:
    src: 'service2.service.j2'
    dest: '/lib/systemd/system/service2.service'
    owner: root
    group: root

- name: 'Enable/Start Service'
  systemd:
    name: 'service2'
    daemon_reload: yes
    enabled: yes
    state: 'started'
  notify: 'Restart service'
